CREATE TABLE user_events
(
    id                   BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    event_id             VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    user_id              BIGINT                                            NOT NULL,
    event_type           VARCHAR(40) CHARACTER SET ascii                   NOT NULL,
    source_module        VARCHAR(10) CHARACTER SET ascii                   NOT NULL,
    session_id           VARCHAR(64),
    kp_id                BIGINT NULL,
    event_data_json      JSON                                              NOT NULL,
    schema_version       VARCHAR(10) CHARACTER SET ascii                   NOT NULL,
    occurred_at          DATETIME(3) NOT NULL,
    received_at          DATETIME(3) NOT NULL,
    process_status       VARCHAR(16)                                       NOT NULL DEFAULT 'PENDING',
    trace_id             VARCHAR(64),
    payload_hash         CHAR(64) CHARACTER SET ascii COLLATE ascii_bin    NOT NULL,
    payload_hash_version SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    UNIQUE KEY uk_user_events_event_id(event_id),
    KEY                  idx_user_events_user_occurred(user_id,occurred_at),
    KEY                  idx_user_events_user_type_occurred(user_id,event_type,occurred_at),
    KEY                  idx_user_events_status_received(process_status,received_at),
    KEY                  idx_user_events_user_kp(user_id,kp_id),
    CONSTRAINT chk_user_events_status CHECK (process_status IN ('PENDING', 'QUARANTINED', 'PROCESSED', 'FAILED')),
    CONSTRAINT chk_user_events_hash_version CHECK (payload_hash_version >= 1),
    CONSTRAINT chk_user_events_user CHECK (user_id > 0),
    CONSTRAINT chk_user_events_kp CHECK (kp_id IS NULL OR kp_id > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
